### ISSUE TITLE
Verify signature generated online with public key

### ISSUE THREAD

**Issue by guesmihela** [open-eid/browser-token-signing#27]
I'd like to verify that the Generated signature is valid or not. is there any tools to verify the Generated signature online , a function or other way????

**Comment by metsma** [comment]
openssl rsautl -in signature.bin -inkey sign.crt -certin -pkcs -verify -hexdump

**Comment by guesmihela** [comment]
is there  any function  in javascript  to resolve it !!!

**Comment by martinpaljak** [comment]
This is not stackoverflow.

**Comment by guesmihela** [comment]
I know . if you  have a response  you  can help if not  let's others

**Comment by guesmihela** [comment]
it works , comment just for help others who need to do this one  ,  I use https://github.com/digitalbazaar/forge#x509

**Comment by dvas0004** [comment]
Sorry to bring this from the dead, but ever since the recall and re-issuing of the eIDs the ID cards in Estonia are now using ECDSA so you need to take that into account. A quick reference python script:

https://gist.github.com/dvas0004/3f2dbf2a3ce16bdc865766b990da0e6f

Replace with your own certificate and signature which can be easily copy/pasted off the hwcrypto demo site: https://hwcrypto.github.io/demo/
